name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Run Spigot BuildTools for NMS if required
      - name: Setup BuildTools
        if: steps.cache.outputs.cache-hit != 'true'
        run: mkdir BuildTools
      - name: Download BuildTools
        if: steps.cache.outputs.cache-hit != 'true'
        run: wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: 1.16.5
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.16.5
      - name: 1.17.1
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.17.1 --remapped remapped-mojang
      - name: 1.18.1
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.18.1 --remapped remapped-mojang
      - name: Build with Maven
        run: mvn clean package install
      - name: Set release version env variable
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Create release dir and rename jar
        run: mkdir release && mv target/Forbiddizen*.jar release/Forbiddizen-${{ env.RELEASE_VERSION }}-${{ github.run_number }}.jar
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: Forbiddizen-${{ env.RELEASE_VERSION }}-${{ github.run_number }}
          path: release/Forbiddizen*.jar