name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build and release the project
      - name: Maven Build
        run: mvn clean package install
      - name: Set release version
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Name artifact
        run: mkdir release && cp target/Forbiddizen-${{ env.RELEASE_VERSION }}.jar release/Forbiddizen-${{ env.RELEASE_VERSION }}-b${{ github.run_number }}.jar
      #- name: Upload jar
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: Forbiddizen-${{ env.RELEASE_VERSION }}-b${{ github.run_number }}
      #    path: target/Forbiddizen-${{ env.RELEASE_VERSION }}.jar

      # Release build
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          toTag: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.RELEASE_VERSION }}-b${{ github.run_number }}
          release_name: Forbiddizen ${{ env.RELEASE_VERSION }} (Build ${{ github.run_number }})
          body: ${{ steps.build_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/Forbiddizen-${{ env.RELEASE_VERSION }}-b${{ github.run_number }}.jar
          asset_name: Forbiddizen-${{ env.RELEASE_VERSION }}-b${{ github.run_number }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}