name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build and create artifact
      - name: Maven Build
        run: mvn clean package install
      - name: Set release version
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Name artifact
        run: mkdir release && cp target/Forbiddizen-${{ env.RELEASE_VERSION }}.jar release/Forbiddizen-${{ env.RELEASE_VERSION }}-b${{ github.run_number }}.jar

      # Release build
      - name: Build changelog
        run: |
          last_tag=`git describe --tags --abbrev=0`
          changes=`git log --no-merges --format=format:"- %s" "$last_tag..HEAD"`
          if [ -z "$changes" ]; then
            changes="- none"
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "Changes since previous release:" >> $GITHUB_ENV
          echo "$changes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.RELEASE_VERSION }}-b${{ github.run_number }}
          release_name: Forbiddizen ${{ env.RELEASE_VERSION }} (Build ${{ github.run_number }})
          body: ${{ env.CHANGELOG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/Forbiddizen-${{ env.RELEASE_VERSION }}-b${{ github.run_number }}.jar
          asset_name: Forbiddizen-${{ env.RELEASE_VERSION }}-b${{ github.run_number }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}